apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        version: 0.0.1
        track: stable
    spec:
      containers:
      - name: hello-world
        image: elustgarten/sample-nodejsrest
        ports:
        - containerPort: 8081